language: java
dist: trusty
jdk:
  - oraclejdk8
  - openjdk8
before_install:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
  